POST http://localhost:3001/api/cart/addtocart/1/4
Content-Type: application/json

{
  "quantity": 3
}

###
DELETE http://localhost:3001/api/cart/deletecart/1/4
Content-Type: application/json

###
POST http://localhost:3001/api/cart/updatecart/1/1
Content-Type: application/json

{
  "quantity": "2"
}

###
GET http://localhost:3001/api/cart/getcart/1

###
GET http://localhost:3001/api/cart/getcartitem/4

###
GET http://localhost:3001/api/cart/getalldata/1

###
POST http://localhost:3001/api/order/addProduct/1
Content-Type: application/json

{
  "sizeItemId": "1",
  "quantity": "6"
}

###
DELETE http://localhost:3001/api/order/cancel/3

###
POST http://localhost:3001/api/order/moveMultipleFromCartToOrder
Content-Type: application/json

{
  "userId": "1",
  "cartItemIds": [3,2]
}

###
POST http://localhost:3001/api/order/confirmOrder/4
Content-Type: application/json

{
  "shippingAddress": "hau giang", 
  "paymentMethod": "PayPal"
}

###
GET  http://localhost:3001/api/order/orders/total
Content-Type: application/json

{
  "month": "11",
  "year": "2023"
}